### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by MrFastwind** [UnexpectedFeature/unexpectedfeature.github.io#1]
Missing readme with information about tools, and how to add new articles

**Comment by SamueleLorefice** [comment]
Wait, it's this project still on?

**Comment by MrFastwind** [comment]
well technicaly it wasn't closed, and i decided to start writing

**Comment by SamueleLorefice** [comment]
Fair enough

**Comment by MrFastwind** [comment]
Added in commit 4681739
